name: Cypress tests 
on: 
 [push]
jobs:
  cypress-run: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install, run tests and record
        uses: cypress-io/github-action@v2.9.7
        with:
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          runTests: true
          record: true
        env:
         CYPRESS_RECORD_KEY: 87c57539-5522-41fd-8412-9937edeeebfe

